# Generated by Django 3.2.12 on 2024-09-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do produto', null=True, verbose_name='Descrição')),
                ('valor_compra', models.DecimalField(decimal_places=2, help_text='Valor de compra do produto', max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, help_text='Valor de venda do produto', max_digits=10)),
                ('detalhes', models.TextField(blank=True, help_text='Detalhes adicionais sobre o produto', null=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso do produto em quilogramas', max_digits=10)),
                ('quantidade', models.IntegerField(help_text='Quantidade disponível em estoque')),
                ('vencimento', models.DateField(help_text='Data de vencimento do produto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
