# Generated by Django 3.2.12 on 2024-10-21 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, help_text='Valor de venda do produto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
