# Generated by Django 4.2.16 on 2024-10-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso do produto em quilogramas', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento do produto', null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=14, verbose_name='Código'),
        ),
    ]
