# Generated by Django 3.2.12 on 2024-09-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
