# Generated by Django 3.2.12 on 2024-09-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0002_auto_20240915_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_produto', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade_venda',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade vendida de produtos'),
        ),
    ]
