# Generated by Django 3.2.12 on 2024-10-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_itemvenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade_venda',
        ),
    ]
